version: "3.8"

services:
  db:
    image: postgres:14.5-bullseye
    container_name: petshop-ave-maria
    environment:
      POSTGRES_DB: "petshop-ave-maria"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
    volumes: 
      - /var/www/databases/petshop-ave-maria:/var/lib/postgresql/data
    networks:
      -  net-petshop-ave-maria-database


networks: 
  net-petshop-ave-maria-database:
    driver: bridge

