services:
  db:
    container_name: docker_pg
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    volumes:
      - dbdata:/data/api
    network_mode: bridge

volumes:
  dbdata:
    driver: local