GET http://localhost:3302/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhNmIyMWJjLWM0YmQtNDFlOC04OTA2LTM3NjI2MGY1MmM2YiIsIm5hbWUiOiJMZWFuZHJvIFJvY2hhIiwidXNlcm5hbWUiOiJsZWFuZHJvLXdyb2NoYSIsImlhdCI6MTY2MDE3ODYyNywiZXhwIjoxNjYwMTc4NzQ3fQ.FCT3A68QE1NKWG16OizjtCXRX2UpcqyGGwUSuNyyBso